server.port=8081
# The port can be overridden by the PORT environment variable in Cloud Run
server.port=${PORT:8081}
spring.main.allow-bean-definition-overriding=true
logging.level.info.esblurock.background=INFO
