//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.3-b24-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.10.09 at 04:07:42 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://blurock.forbrf.lth.se/thermo", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package se.lth.forbrf.blurock.thermo;
