include ../etc/MakeDef.defs

###############################################################
# Program specific definitions
#   PROGNAME    - The name of the program and the directory
#   STD_LIBRARIES   - The available libraries to use
#   ALL_PROGS       - Those progs to be compiled
#   ALL_SOURCES     - The list of source files
#   ALL_OBJECTS     - The list of object files
#   EXTRAS          - The list of extra files associated with program
###############################################################
PROGNAME   = property
ALL_PROGS = str_form library
HFILES     = mol0.h molprops.h

ALL_SOURCES = \
      propertytypes.c aprops.c propout.c pstore.c types.c util.c

ALL_OBJECTS = \
      propertytypes.o aprops.o propout.o pstore.o types.o util.o

COMMANDFILES = util.cmd

EXTRAS = 


include ../etc/MakeDef.prgs
