printmolecule.sh butane
printmolecule.sh isobutane
printmolecule.sh 1-butyl-radical
printmolecule.sh 2-butyl-radical
printmolecule.sh isobutyl-radical
printmolecule.sh tertbutyl-radical
printmolecule.sh 1-butene
printmolecule.sh 2-butene
printmolecule.sh isobutene
printmolecule.sh cyclobutane
printmolecule.sh 1-butene-1-yl-radical
printmolecule.sh 1-butene-2-yl-radical
printmolecule.sh 1-butene-3-yl-radical
printmolecule.sh 2-butene-2-yl-radical
printmolecule.sh 2-butene-1-yl-radical
printmolecule.sh 3-butene-1-yl-radical
printmolecule.sh cyclobutyl-radical
printmolecule.sh prop-1-en-2-methyl-1-yl-radical
printmolecule.sh 1-butyne
printmolecule.sh 2-butyne
printmolecule.sh 1,3-butadiene
printmolecule.sh 1,2-butadiene
printmolecule.sh cyclobutene
printmolecule.sh 2-butynyl-radical
printmolecule.sh 1-butyn-3-yl
printmolecule.sh 1,3-butadiene-1-yl
printmolecule.sh 1,3-butadiene-2-yl
printmolecule.sh 1,2-butadiene-4-yl
printmolecule.sh butyne-1-yl-radical
printmolecule.sh cyclobutadiene
printmolecule.sh 1-butyne-3-ene
printmolecule.sh 1-butene-3-yne-1-yl
printmolecule.sh 1-butene-3-yne-2-yl
printmolecule.sh butadiyne
printmolecule.sh butadiynyl
