include ../etc/MakeDef.defs

###############################################################
# Program specific definitions
#   PROGNAME    - The name of the program and the directory
#   STD_LIBRARIES   - The available libraries to use
#   ALL_PROGS       - Those progs to be compiled
#   ALL_SOURCES     - The list of source files
#   ALL_OBJECTS     - The list of object files
#   EXTRAS          - The list of extra files associated with program
###############################################################
PROGNAME   = graphs
ALL_PROGS = str_form library
HFILES     = mol0.h molprops.h

ALL_SOURCES = \
       graph0.c graph1.c graph2.c graph3.c \
       subgraph.c pairset.c paths.c

ALL_OBJECTS = \
       graph0.o graph1.o graph2.o graph3.o \
       subgraph.o pairset.o paths.o

COMMANDFILES = util.cmd

EXTRAS = 


include ../etc/MakeDef.prgs
